### ISSUE TITLE
Get Complete Course Details

### ISSUE THREAD

**Issue by ahmedradwan21** [dragonsbootcampllc/DragonsBootcampLMS#54]
**Description**:  
Develop an endpoint to fetch all course details (name, description, instructor, etc.) for users to view before registering.

**Expected Endpoints**:  
- **Retrieve Course Details**:  
  `GET /courses/:courseId/details`  
  *Purpose*: Retrieve complete details of a course.

**Updated Model**:  
`Course`
- `id` (UUID, Primary Key)
- `name` (String)
- `description` (Text)
- `educator_id` (Foreign Key, References `User`)
- `lectures_count` (Integer)
- `created_at` (Timestamp)
- `updated_at` (Timestamp)

**Comment by ahmedehab0** [comment]
what is the diffrence between this route and the getCourseByid route implemented with the course crud operation, I see that it is pretty much the same
